[package]
name = "fuba"
version = "0.1.0"
authors = ["Peter Helbing <peter@abulafia.org>"]
license = "GPL-2.0-or-later"

[dependencies]
clap = "2.31"
num_cpus = "1.0"
petgraph = "0.4"
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"