name = "1974 FIFA World Cup"
# seed = "12345678"

root = "rank"

team = [
    { id = "frg", name = "West Germany", elo = 2209 },
    { id = "chi", name = "Chile", elo = 1780 },
    { id = "aus", name = "Australia", elo = 1693 },
    { id = "gdr", name = "East Germany", elo = 1940 },

    { id = "bra", name = "Brazil", elo = 2116 },
    { id = "yug", name = "Yugoslavia", elo = 1934 },
    { id = "sco", name = "Scotland", elo = 1821 },
    { id = "zai", name = "Zaire", elo = 1787 },

    { id = "uru", name = "Uruguay", elo = 1754 },
    { id = "ned", name = "Netherlands", elo = 1839 },
    { id = "bul", name = "Bulgaria", elo = 1819 },
    { id = "swe", name = "Sweden", elo = 1883 },

    { id = "ita", name = "Italy", elo = 1999 },
    { id = "hai", name = "Haiti", elo = 1609 },
    { id = "arg", name = "Argentina", elo = 1894 },
    { id = "pol", name = "Poland", elo = 1959 },
]

[[format]]
id = "f_group"
mode = "roundrobin"
order = [[1,2], [3,4],
         [1,3], [2,4],
         [1,4], [2,3]]
neutral = true
points_for_win = 2
rank_by = ["points", "goaldiff", "goals", "vspoints", "vsgoaldiff", "vsgoals"]

[[format]]
id = "f_playoff"
mode = "playoff"
random = false
neutral = true
rank_by = ["extra", "penalties"]

[[format]]
id = "f_ranking"
mode = "ranking"
rank_by = []

[[round]]
id = "group-1"
name = "Group 1"
format = "f_group"
entrant = [
    { id = "frg" },
    { id = "chi" },
    { id = "aus" },
    { id = "gdr" },
]

[[round]]
id = "group-2"
name = "Group 2"
format = "f_group"
entrant = [
    { id = "bra" },
    { id = "yug" },
    { id = "sco" },
    { id = "zai" },
]

[[round]]
id = "group-3"
name = "Group 3"
format = "f_group"
entrant = [
    { id = "uru" },
    { id = "ned" },
    { id = "bul" },
    { id = "swe" },
]

[[round]]
id = "group-4"
name = "Group 4"
format = "f_group"
entrant = [
    { id = "ita" },
    { id = "hai" },
    { id = "arg" },
    { id = "pol" },
]

[[round]]
id = "group-a"
name = "Group A"
format = "f_group"
entrant = [
    { prev = "group-1", pos = 1 },
    { prev = "group-2", pos = 2 },
    { prev = "group-3", pos = 1 },
    { prev = "group-4", pos = 2 },
]

[[round]]
id = "group-b"
name = "Group B"
format = "f_group"
entrant = [
    { prev = "group-2", pos = 1 },
    { prev = "group-1", pos = 2 },
    { prev = "group-4", pos = 1 },
    { prev = "group-3", pos = 2 },
]

[[round]]
id = "3p"
name = "Third place play-off"
format = "f_playoff"
entrant = [
    { prev = "group-a", pos = 2 },
    { prev = "group-b", pos = 2 },
]

[[round]]
id = "fi"
name = "Final"
format = "f_playoff"
entrant = [
    { prev = "group-a", pos = 1 },
    { prev = "group-b", pos = 1 },
]

[[round]]
id = "rank"
name = "Final ranking"
format = "f_ranking"
entrant = [
    { prev = "fi", pos = 1 },
    { prev = "fi", pos = 2 },
    { prev = "3p", pos = 1 },
    { prev = "3p", pos = 2 },
]