name = "1982 FIFA World Cup"
seed = "12345678"

root = "rank"

team = [
    { id = "ita", name = "Italy", elo = 1892 },
    { id = "pol", name = "Poland", elo = 1959 },
    { id = "per", name = "Peru", elo = 1775 },
    { id = "cmr", name = "Cameroon", elo = 1665 },

    { id = "frg", name = "West Germany", elo = 2108 },
    { id = "alg", name = "Algeria", elo = 1645 },
    { id = "chi", name = "Chile", elo = 1771 },
    { id = "aut", name = "Austria", elo = 1917 },

    { id = "arg", name = "Argentina", elo = 2003 },
    { id = "bel", name = "Belgium", elo = 1913 },
    { id = "hun", name = "Hungary", elo = 1799 },
    { id = "slv", name = "El Salvador", elo = 1610 },

    { id = "eng", name = "England", elo = 1963 },
    { id = "fra", name = "France", elo = 1879 },
    { id = "tch", name = "Czechoslovakia", elo = 1898 },
    { id = "kuw", name = "Kuwait", elo = 1632 },

    { id = "esp", name = "Spain", elo = 1988 },
    { id = "hon", name = "Honduras", elo = 1600 },
    { id = "yug", name = "Yugoslavia", elo = 1916 },
    { id = "nir", name = "Northern Ireland", elo = 1740 },

    { id = "bra", name = "Brazil", elo = 2092 },
    { id = "urs", name = "Soviet Union", elo = 2010 },
    { id = "sco", name = "Scotland", elo = 1837 },
    { id = "nzl", name = "New Zealand", elo = 1600 },
]

[[format]]
id = "f_group1"
mode = "roundrobin"
order = [[1,2], [3,4],
         [1,3], [2,4],
         [2,3], [1,4]]
neutral = true
points_for_win = 2
rank_by = ["points", "goaldiff", "goals", "vspoints", "vsgoaldiff", "vsgoals"]

[[format]]
id = "f_group2"
mode = "roundrobin"
order = [[1,2], [2,3], [3,1]]
neutral = true
points_for_win = 2
rank_by = ["points", "goaldiff", "goals", "vspoints", "vsgoaldiff", "vsgoals"]

[[format]]
id = "f_playoff"
mode = "playoff"
random = false
neutral = true
rank_by = ["extra", "penalties"]

[[format]]
id = "f_ranking"
mode = "ranking"
rank_by = []

[[round]]
id = "group-1"
name = "Group 1"
format = "f_group1"
entrant = [
    { id = "ita" },
    { id = "pol" },
    { id = "per" },
    { id = "cmr" },
]

[[round]]
id = "group-2"
name = "Group 2"
format = "f_group1"
entrant = [
    { id = "frg" },
    { id = "alg" },
    { id = "chi" },
    { id = "aut" },
]

[[round]]
id = "group-3"
name = "Group 3"
format = "f_group1"
entrant = [
    { id = "arg" },
    { id = "bel" },
    { id = "hun" },
    { id = "slv" },
]

[[round]]
id = "group-4"
name = "Group 4"
format = "f_group1"
entrant = [
    { id = "eng" },
    { id = "fra" },
    { id = "tch" },
    { id = "kuw" },
]

[[round]]
id = "group-5"
name = "Group 5"
format = "f_group1"
entrant = [
    { id = "esp" },
    { id = "hon" },
    { id = "yug" },
    { id = "nir" },
]

[[round]]
id = "group-6"
name = "Group 6"
format = "f_group1"
entrant = [
    { id = "bra" },
    { id = "urs" },
    { id = "sco" },
    { id = "nzl" },
]

[[round]]
id = "group-a"
name = "Group A"
format = "f_group2"
entrant = [
    { prev = "group-1", pos = 1 },
    { prev = "group-3", pos = 1 },
    { prev = "group-6", pos = 2 },
]

[[round]]
id = "group-b"
name = "Group B"
format = "f_group2"
entrant = [
    { prev = "group-2", pos = 1 },
    { prev = "group-4", pos = 1 },
    { prev = "group-5", pos = 2 },
]

[[round]]
id = "group-c"
name = "Group C"
format = "f_group2"
entrant = [
    { prev = "group-1", pos = 2 },
    { prev = "group-3", pos = 2 },
    { prev = "group-6", pos = 1 },
]

[[round]]
id = "group-d"
name = "Group D"
format = "f_group2"
entrant = [
    { prev = "group-2", pos = 2 },
    { prev = "group-4", pos = 2 },
    { prev = "group-5", pos = 1 },
]

[[round]]
id = "sf"
name = "Semifinals"
format = "f_playoff"
entrant = [
    { prev = "group-a", pos = 1 },
    { prev = "group-c", pos = 1 },
    { prev = "group-b", pos = 1 },
    { prev = "group-d", pos = 1 },
]

[[round]]
id = "3p"
name = "Third place play-off"
format = "f_playoff"
entrant = [
    { prev = "sf", pos = 3 },
    { prev = "sf", pos = 4 },
]

[[round]]
id = "fi"
name = "Final"
format = "f_playoff"
entrant = [
    { prev = "sf", pos = 1 },
    { prev = "sf", pos = 2 },
]

[[round]]
id = "rank"
name = "Final ranking"
format = "f_ranking"
entrant = [
    { prev = "fi", pos = 1 },
    { prev = "fi", pos = 2 },
    { prev = "3p", pos = 1 },
    { prev = "3p", pos = 2 },
]