name = "1998 FIFA World Cup"
seed = "12345678"

root = "rank"

team = [
    { id = "bra", name = "Brazil", elo = 2095 },
    { id = "sco", name = "Scotland", elo = 1777 },
    { id = "mar", name = "Morocco", elo = 1729 },
    { id = "nor", name = "Norway", elo = 1904 },

    { id = "ita", name = "Italy", elo = 1970 },
    { id = "chi", name = "Chile", elo = 1779 },
    { id = "cmr", name = "Cameroon", elo = 1598 },
    { id = "aut", name = "Austria", elo = 1717 },

    { id = "fra", name = "France", elo = 2103 },
    { id = "rsa", name = "South Africa", elo = 1643 },
    { id = "ksa", name = "Saudi Arabia", elo = 1649 },
    { id = "den", name = "Denmark", elo = 1880 },

    { id = "esp", name = "Spain", elo = 2040 },
    { id = "ngr", name = "Nigeria", elo = 1707 },
    { id = "par", name = "Paraguay", elo = 1739 },
    { id = "bul", name = "Bulgaria", elo = 1806 },

    { id = "ned", name = "Netherlands", elo = 1961 },
    { id = "bel", name = "Belgium", elo = 1820 },
    { id = "kor", name = "South Korea", elo = 1767 },
    { id = "mex", name = "Mexico", elo = 1846 },

    { id = "ger", name = "Germany", elo = 2060 },
    { id = "usa", name = "United States", elo = 1760 },
    { id = "yug", name = "Yugoslavia", elo = 1970 },
    { id = "iri", name = "Iran", elo = 1647 },

    { id = "eng", name = "England", elo = 1973 },
    { id = "tun", name = "Tunisia", elo = 1638 },
    { id = "rou", name = "Romania", elo = 1877 },
    { id = "col", name = "Colombia", elo = 1762 },

    { id = "arg", name = "Argentina", elo = 1890 },
    { id = "jpn", name = "Japan", elo = 1737 },
    { id = "jam", name = "Jamaica", elo = 1649 },
    { id = "cro", name = "Croatia", elo = 1871 },
]

[[format]]
id = "f_group"
mode = "roundrobin"
order = [[1,2], [3,4],
         [1,3], [4,2],
         [4,1], [2,3]]
neutral = true
rank_by = ["points", "goaldiff", "goals", "vspoints", "vsgoaldiff", "vsgoals"]

[[format]]
id = "f_playoff"
mode = "playoff"
random = false
neutral = true
rank_by = ["extra", "penalties"]

[[format]]
id = "f_ranking"
mode = "ranking"
rank_by = []

[[round]]
id = "group-a"
name = "Group A"
format = "f_group"
entrant = [
    { id = "bra" },
    { id = "nor" },
    { id = "mar" },
    { id = "sco" },
]

[[round]]
id = "group-b"
name = "Group B"
format = "f_group"
entrant = [
    { id = "ita" },
    { id = "chi" },
    { id = "cmr" },
    { id = "aut" },
]

[[round]]
id = "group-c"
name = "Group C"
format = "f_group"
entrant = [
    { id = "fra" },
    { id = "rsa" },
    { id = "ksa" },
    { id = "den" },
]

[[round]]
id = "group-d"
name = "Group D"
format = "f_group"
entrant = [
    { id = "esp" },
    { id = "ngr" },
    { id = "par" },
    { id = "bul" },
]

[[round]]
id = "group-e"
name = "Group E"
format = "f_group"
entrant = [
    { id = "ned" },
    { id = "bel" },
    { id = "kor" },
    { id = "mex" },
]

[[round]]
id = "group-f"
name = "Group F"
format = "f_group"
entrant = [
    { id = "ger" },
    { id = "usa" },
    { id = "yug" },
    { id = "iri" },
]

[[round]]
id = "group-g"
name = "Group G"
format = "f_group"
entrant = [
    { id = "eng" },
    { id = "tun" },
    { id = "rou" },
    { id = "col" },
]

[[round]]
id = "group-h"
name = "Group H"
format = "f_group"
entrant = [
    { id = "arg" },
    { id = "jpn" },
    { id = "jam" },
    { id = "cro" },
]

[[round]]
id = "r16"
name = "Round of 16"
format = "f_playoff"
entrant = [
    { prev = "group-b", pos = 1 },
    { prev = "group-a", pos = 2 },
    { prev = "group-a", pos = 1 },
    { prev = "group-b", pos = 2 },
    { prev = "group-c", pos = 1 },
    { prev = "group-d", pos = 2 },
    { prev = "group-d", pos = 1 },
    { prev = "group-c", pos = 2 },
    { prev = "group-f", pos = 1 },
    { prev = "group-e", pos = 2 },
    { prev = "group-e", pos = 1 },
    { prev = "group-f", pos = 2 },
    { prev = "group-g", pos = 1 },
    { prev = "group-h", pos = 2 },
    { prev = "group-h", pos = 1 },
    { prev = "group-g", pos = 2 },
]

[[round]]
id = "qf"
name = "Quarterfinals"
format = "f_playoff"
entrant = [
    { prev = "r16", pos = 1 },
    { prev = "r16", pos = 3 },
    { prev = "r16", pos = 2 },
    { prev = "r16", pos = 4 },
    { prev = "r16", pos = 6 },
    { prev = "r16", pos = 8 },
    { prev = "r16", pos = 5 },
    { prev = "r16", pos = 7 },
]

[[round]]
id = "sf"
name = "Semifinals"
format = "f_playoff"
entrant = [
    { prev = "qf", pos = 2 },
    { prev = "qf", pos = 3 },
    { prev = "qf", pos = 1 },
    { prev = "qf", pos = 4 },
]

[[round]]
id = "3p"
name = "Third place play-off"
format = "f_playoff"
entrant = [
    { prev = "sf", pos = 3 },
    { prev = "sf", pos = 4 },
]

[[round]]
id = "fi"
name = "Final"
format = "f_playoff"
entrant = [
    { prev = "sf", pos = 1 },
    { prev = "sf", pos = 2 },
]

[[round]]
id = "rank"
name = "Final ranking"
format = "f_ranking"
entrant = [
    { prev = "fi", pos = 1 },
    { prev = "fi", pos = 2 },
    { prev = "3p", pos = 1 },
    { prev = "3p", pos = 2 },
]