name = "1978 FIFA World Cup"
seed = "12345678"

root = "rank"

team = [
    { id = "arg", name = "Argentina", elo = 2025 },
    { id = "hun", name = "Hungary", elo = 1921 },
    { id = "fra", name = "France", elo = 1881 },
    { id = "ita", name = "Italy", elo = 1935 },

    { id = "frg", name = "West Germany", elo = 2096 },
    { id = "pol", name = "Poland", elo = 1929 },
    { id = "mex", name = "Mexico", elo = 1793 },
    { id = "tun", name = "Tunisia", elo = 1680 },

    { id = "bra", name = "Brazil", elo = 2078 },
    { id = "swe", name = "Sweden", elo = 1792 },
    { id = "esp", name = "Spain", elo = 1959 },
    { id = "aut", name = "Austria", elo = 1860 },

    { id = "ned", name = "Netherlands", elo = 2092 },
    { id = "irn", name = "Iran", elo = 1773 },
    { id = "per", name = "Peru", elo = 1755 },
    { id = "sco", name = "Scotland", elo = 1944 },
]

[[format]]
id = "f_group"
mode = "roundrobin"
order = [[1,2], [3,4],
         [1,3], [2,4],
         [1,4], [2,3]]
neutral = true
points_for_win = 2
rank_by = ["points", "goaldiff", "goals", "vspoints", "vsgoaldiff", "vsgoals"]

[[format]]
id = "f_playoff"
mode = "playoff"
random = false
neutral = true
rank_by = ["extra", "penalties"]

[[format]]
id = "f_final"
mode = "playoff"
random = false
neutral = true
rank_by = ["extra", "replayonce", "penalties"]

[[format]]
id = "f_ranking"
mode = "ranking"
rank_by = []

[[round]]
id = "group-1"
name = "Group 1"
format = "f_group"
entrant = [
    { id = "arg" },
    { id = "hun" },
    { id = "fra" },
    { id = "ita" },
]

[[round]]
id = "group-2"
name = "Group 2"
format = "f_group"
entrant = [
    { id = "frg" },
    { id = "pol" },
    { id = "mex" },
    { id = "tun" },
]

[[round]]
id = "group-3"
name = "Group 3"
format = "f_group"
entrant = [
    { id = "bra" },
    { id = "swe" },
    { id = "esp" },
    { id = "aut" },
]

[[round]]
id = "group-4"
name = "Group 4"
format = "f_group"
entrant = [
    { id = "ned" },
    { id = "irn" },
    { id = "per" },
    { id = "sco" },
]

[[round]]
id = "group-a"
name = "Group A"
format = "f_group"
entrant = [
    { prev = "group-1", pos = 1 },
    { prev = "group-2", pos = 2 },
    { prev = "group-3", pos = 1 },
    { prev = "group-4", pos = 2 },
]

[[round]]
id = "group-b"
name = "Group B"
format = "f_group"
entrant = [
    { prev = "group-2", pos = 1 },
    { prev = "group-1", pos = 2 },
    { prev = "group-4", pos = 1 },
    { prev = "group-3", pos = 2 },
]

[[round]]
id = "3p"
name = "Third place play-off"
format = "f_playoff"
entrant = [
    { prev = "group-a", pos = 2 },
    { prev = "group-b", pos = 2 },
]

[[round]]
id = "fi"
name = "Final"
format = "f_final"
entrant = [
    { prev = "group-a", pos = 1 },
    { prev = "group-b", pos = 1 },
]

[[round]]
id = "rank"
name = "Final ranking"
format = "f_ranking"
entrant = [
    { prev = "fi", pos = 1 },
    { prev = "fi", pos = 2 },
    { prev = "3p", pos = 1 },
    { prev = "3p", pos = 2 },
]