name = "1966 FIFA World Cup"
seed = "12345678"

root = "rank"

team = [
    { id = "eng", name = "England", elo = 2091 },
    { id = "uru", name = "Uruguay", elo = 1846 },
    { id = "mex", name = "Mexico", elo = 1866 },
    { id = "fra", name = "France", elo = 1754 },

    { id = "arg", name = "Argentina", elo = 1964 },
    { id = "esp", name = "Spain", elo = 1892 },
    { id = "frg", name = "West Germany", elo = 1947 },
    { id = "sui", name = "Switzerland", elo = 1641 },

    { id = "bra", name = "Brazil", elo = 2018 },
    { id = "bul", name = "Bulgaria", elo = 1797 },
    { id = "por", name = "Portugal", elo = 1829 },
    { id = "hun", name = "Hungary", elo = 1959 },

    { id = "ita", name = "Italy", elo = 1967 },
    { id = "chi", name = "Chile", elo = 1750 },
    { id = "urs", name = "Soviet Union", elo = 2001 },
    { id = "prk", name = "North Korea", elo = 1838 },
]

[[format]]
id = "f_group"
mode = "roundrobin"
order = [[1,2], [3,4],
         [1,3], [2,4],
         [1,4], [2,3]]
neutral = true
points_for_win = 2
rank_by = ["points", "goalquot", "goals", "vspoints", "vsgoalquot", "vsgoals"]

[[format]]
id = "f_playoff"
mode = "playoff"
random = false
neutral = true
rank_by = ["extra"]

[[format]]
id = "f_final"
mode = "playoff"
random = false
neutral = true
rank_by = ["extra", "replayalways"]

[[format]]
id = "f_ranking"
mode = "ranking"
rank_by = []

[[round]]
id = "group-1"
name = "Group 1"
format = "f_group"
entrant = [
    { id = "eng" },
    { id = "uru" },
    { id = "mex" },
    { id = "fra" },
]

[[round]]
id = "group-2"
name = "Group 2"
format = "f_group"
entrant = [
    { id = "arg" },
    { id = "esp" },
    { id = "frg" },
    { id = "sui" },
]

[[round]]
id = "group-3"
name = "Group 3"
format = "f_group"
entrant = [
    { id = "bra" },
    { id = "bul" },
    { id = "por" },
    { id = "hun" },
]

[[round]]
id = "group-4"
name = "Group 4"
format = "f_group"
entrant = [
    { id = "ita" },
    { id = "chi" },
    { id = "urs" },
    { id = "prk" },
]

[[round]]
id = "qf"
name = "Quarterfinals"
format = "f_playoff"
entrant = [
    { prev = "group-1", pos = 1 },
    { prev = "group-2", pos = 2 },
    { prev = "group-2", pos = 1 },
    { prev = "group-1", pos = 2 },
    { prev = "group-3", pos = 1 },
    { prev = "group-4", pos = 2 },
    { prev = "group-4", pos = 1 },
    { prev = "group-3", pos = 2 },
]

[[round]]
id = "sf"
name = "Semifinals"
format = "f_playoff"
entrant = [
    { prev = "qf", pos = 1 },
    { prev = "qf", pos = 3 },
    { prev = "qf", pos = 2 },
    { prev = "qf", pos = 4 },
]

[[round]]
id = "3p"
name = "Third place play-off"
format = "f_playoff"
entrant = [
    { prev = "sf", pos = 3 },
    { prev = "sf", pos = 4 },
]

[[round]]
id = "fi"
name = "Final"
format = "f_final"
entrant = [
    { prev = "sf", pos = 1 },
    { prev = "sf", pos = 2 },
]

[[round]]
id = "rank"
name = "Final ranking"
format = "f_ranking"
entrant = [
    { prev = "fi", pos = 1 },
    { prev = "fi", pos = 2 },
    { prev = "3p", pos = 1 },
    { prev = "3p", pos = 2 },
]