name = "2002 FIFA World Cup"
seed = "12345678"

root = "rank"

team = [
    { id = "fra", name = "France", elo = 2096 },
    { id = "sen", name = "Senegal", elo = 1702 },
    { id = "uru", name = "Uruguay", elo = 1812 },
    { id = "den", name = "Denmark", elo = 1885 },

    { id = "esp", name = "Spain", elo = 1963 },
    { id = "slo", name = "Slovenia", elo = 1743 },
    { id = "par", name = "Paraguay", elo = 1729 },
    { id = "rsa", name = "South Africa", elo = 1645 },

    { id = "bra", name = "Brazil", elo = 1867 },
    { id = "tur", name = "Turkey", elo = 1757 },
    { id = "chn", name = "China", elo = 1700 },
    { id = "crc", name = "Costa Rica", elo = 1757 },

    { id = "kor", name = "South Korea", elo = 1834 },
    { id = "pol", name = "Poland", elo = 1733 },
    { id = "usa", name = "United States", elo = 1809 },
    { id = "por", name = "Portugal", elo = 1980 },

    { id = "ger", name = "Germany", elo = 1870 },
    { id = "ksa", name = "Saudi Arabia", elo = 1706 },
    { id = "irl", name = "Ireland", elo = 1874 },
    { id = "cmr", name = "Cameroon", elo = 1808 },

    { id = "arg", name = "Argentina", elo = 2015 },
    { id = "ngr", name = "Nigeria", elo = 1769 },
    { id = "eng", name = "England", elo = 1924 },
    { id = "swe", name = "Sweden", elo = 1864 },

    { id = "ita", name = "Italy", elo = 2009 },
    { id = "ecu", name = "Ecuador", elo = 1726 },
    { id = "cro", name = "Croatia", elo = 1880 },
    { id = "mex", name = "Mexico", elo = 1832 },

    { id = "jpn", name = "Japan", elo = 1953 },
    { id = "bel", name = "Belgium", elo = 1838 },
    { id = "rus", name = "Russia", elo = 1801 },
    { id = "tun", name = "Tunisia", elo = 1626 },
]

[[format]]
id = "f_group"
mode = "roundrobin"
order = [[1,2], [3,4],
         [1,3], [4,2],
         [4,1], [2,3]]
neutral = true
rank_by = ["points", "goaldiff", "goals", "vspoints", "vsgoaldiff", "vsgoals"]

[[format]]
id = "f_playoff"
mode = "playoff"
random = false
neutral = true
rank_by = ["extra", "penalties"]

[[format]]
id = "f_ranking"
mode = "ranking"
rank_by = []

[[round]]
id = "group-a"
name = "Group A"
format = "f_group"
entrant = [
    { id = "fra" },
    { id = "sen" },
    { id = "uru" },
    { id = "den" },
]

[[round]]
id = "group-b"
name = "Group B"
format = "f_group"
entrant = [
    { id = "esp" },
    { id = "slo" },
    { id = "par" },
    { id = "rsa" },
]

[[round]]
id = "group-c"
name = "Group C"
format = "f_group"
entrant = [
    { id = "bra" },
    { id = "tur" },
    { id = "chn" },
    { id = "crc" },
]

[[round]]
id = "group-d"
name = "Group D"
format = "f_group"
entrant = [
    { id = "kor" },
    { id = "pol" },
    { id = "usa" },
    { id = "por" },
]

[[round]]
id = "group-e"
name = "Group E"
format = "f_group"
entrant = [
    { id = "ger" },
    { id = "ksa" },
    { id = "irl" },
    { id = "cmr" },
]

[[round]]
id = "group-f"
name = "Group F"
format = "f_group"
entrant = [
    { id = "arg" },
    { id = "ngr" },
    { id = "eng" },
    { id = "swe" },
]

[[round]]
id = "group-g"
name = "Group G"
format = "f_group"
entrant = [
    { id = "ita" },
    { id = "ecu" },
    { id = "cro" },
    { id = "mex" },
]

[[round]]
id = "group-h"
name = "Group H"
format = "f_group"
entrant = [
    { id = "jpn" },
    { id = "bel" },
    { id = "rus" },
    { id = "tun" },
]

[[round]]
id = "r16"
name = "Round of 16"
format = "f_playoff"
entrant = [
    { prev = "group-e", pos = 1 },
    { prev = "group-b", pos = 2 },
    { prev = "group-a", pos = 1 },
    { prev = "group-f", pos = 2 },
    { prev = "group-f", pos = 1 },
    { prev = "group-a", pos = 2 },
    { prev = "group-b", pos = 1 },
    { prev = "group-e", pos = 2 },
    { prev = "group-g", pos = 1 },
    { prev = "group-d", pos = 2 },
    { prev = "group-c", pos = 1 },
    { prev = "group-h", pos = 2 },
    { prev = "group-h", pos = 1 },
    { prev = "group-c", pos = 2 },
    { prev = "group-d", pos = 1 },
    { prev = "group-g", pos = 2 },
]

[[round]]
id = "qf"
name = "Quarterfinals"
format = "f_playoff"
entrant = [
    { prev = "r16", pos = 2 },
    { prev = "r16", pos = 6 },
    { prev = "r16", pos = 1 },
    { prev = "r16", pos = 5 },
    { prev = "r16", pos = 4 },
    { prev = "r16", pos = 8 },
    { prev = "r16", pos = 3 },
    { prev = "r16", pos = 7 },
]

[[round]]
id = "sf"
name = "Semifinals"
format = "f_playoff"
entrant = [
    { prev = "qf", pos = 2 },
    { prev = "qf", pos = 3 },
    { prev = "qf", pos = 1 },
    { prev = "qf", pos = 4 },
]

[[round]]
id = "3p"
name = "Third place play-off"
format = "f_playoff"
entrant = [
    { prev = "sf", pos = 3 },
    { prev = "sf", pos = 4 },
]

[[round]]
id = "fi"
name = "Final"
format = "f_playoff"
entrant = [
    { prev = "sf", pos = 1 },
    { prev = "sf", pos = 2 },
]

[[round]]
id = "rank"
name = "Final ranking"
format = "f_ranking"
entrant = [
    { prev = "fi", pos = 1 },
    { prev = "fi", pos = 2 },
    { prev = "3p", pos = 1 },
    { prev = "3p", pos = 2 },
]